package com.avaje.ebean.config.dbplatform;

import com.avaje.ebean.BackgroundExecutor;
import com.avaje.ebean.config.GlobalProperties;
import javax.sql.DataSource;

public class HsqldbPlatform
  extends DatabasePlatform
{
  public HsqldbPlatform()
  {
    this.name = "hsqldb";
    this.dbEncrypt = new H2DbEncrypt();
    
    boolean useIdentity = GlobalProperties.getBoolean("ebean.hsqldb.useIdentity", true);
    
    IdType idType = useIdentity ? IdType.IDENTITY : IdType.SEQUENCE;
    this.dbIdentity.setIdType(idType);
    
    this.dbIdentity.setSupportsGetGeneratedKeys(true);
    this.dbIdentity.setSupportsSequence(true);
    this.dbIdentity.setSupportsIdentity(true);
    
    this.openQuote = "\"";
    this.closeQuote = "\"";
    
    this.dbTypeMap.put(4, new DbType("integer", false));
    
    this.dbDdlSyntax.setDropIfExists("if exists");
    this.dbDdlSyntax.setDisableReferentialIntegrity("SET DATABASE REFERENTIAL INTEGRITY FALSE");
    this.dbDdlSyntax.setEnableReferentialIntegrity("SET DATABASE REFERENTIAL INTEGRITY TRUE");
    this.dbDdlSyntax.setForeignKeySuffix("on delete restrict on update restrict");
    this.dbDdlSyntax.setIdentity("GENERATED BY DEFAULT AS IDENTITY (START WITH 1) ");
  }
  
  public IdGenerator createSequenceIdGenerator(BackgroundExecutor be, DataSource ds, String seqName, int batchSize)
  {
    return new H2SequenceIdGenerator(be, ds, seqName, batchSize);
  }
}
